[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
refund = "GuSMF3URMDTyW2cqUpmq4U1ZjxNcoc9VwLzcfEJf5kpC"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
