[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
anchor_escrow = "2zJif8t3RNLwxse99ATjJHDgM88F5voE1uctVF9oe7u5"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
