// src/constants.ts

export const CALLBACK_DATA = {
  START_NEW_GAME: "START_NEW_GAME",
  CHECK_BALANCE: "CHECK_BALANCE",
  GET_WALLET_KEY: "GET_WALLET_KEY",
  GAME_PUMP: "GAME_PUMP",
  GAME_PASS: "GAME_PASS",
};
